### ISSUE TITLE
License, pretty please?

### ISSUE THREAD

**Issue by newbthenewbd** [n-yoda/TintDisplay#1]
Applications so exemplary in their excellence are quite rare, heartfelt thanks for making this one!

With only a few minor automatic fixes by Xcode and a [typo correction](https://github.com/n-yoda/TintDisplay/blob/master/TintDisplay/AppDelegate.swift#L36), I could get it up to date and running, which instantly solved my issues with the official Apple-flavored version... Except, technicalegally I shouldn't have, as all the rights are reserved, the only rights I have are the ones GitHub mandates in its ToS :( Care to [choose a license](https://choosealicense.com/)?

Thank you so much!

**Comment by n-yoda** [comment]
Sorry for the late response. I'm surprised to hear it still works. Thanks for finding the typo. I added Apache License. Does that work for you?

**Comment by newbthenewbd** [comment]
A week's time ain't a late response at all, especially with such great news :) Of course it works, both as to the working and the license - huge thanks!
